var Animal, Bear,
  extend = function(child, parent) {
    for (var key in parent) {
      if (hasProp.call(parent, key)) {
        child[key] = parent[key];
      }
    }

    // creates child.prototype
    function Ctor() {
    }
    // because you want to set child.prototype.__proto__ = parent.prototype
    Ctor.prototype = parent.prototype;
    // When an instance of an object is created,
    // the __proto__ property is updated to point to the constructor’s prototype
    child.prototype = new Ctor();
    child.__super__ = parent.prototype;
    return child;
  },
  hasProp = {}.hasOwnProperty;

Animal = (function() {
  function Animal(name) {
    this.name = name;
  }

  Animal.prototype.move = function(meters) {
    return console.log(this.name + (" moved " + meters + "m."));
  };

  return Animal;

})();

Bear = (function(superClass) {
  extend(Bear, superClass);

  function Bear() {
    return Bear.__super__.constructor.apply(this, arguments);
  }

  Bear.prototype.move = function() {
    console.log("Dancing...");
    return Bear.__super__.move.call(this, 1);
  };

  return Bear;

})(Animal);

// ---
// generated by coffee-script 1.9.2
